# Copyright 2022 Cognite AS

## Import the Libraries and Modules

In [1]:
import sys
from pathlib import Path

import pandas as pd
import numpy as np

utils = str(Path("../utils").resolve())
if utils not in sys.path:
    sys.path.append(utils)

from cognite_auth import interactive_client

## Create the Cognite Client

In [2]:
client = interactive_client()

C:\Users\JoeO'Bryant\OneDrive - Cognite AS\projects\cognite_python_sdk_training\using-cognite-python-sdk\.venv\Lib\site-packages\ipykernel\ipkernel.py:772: UserWarning: You are using version='7.86.0' of the SDK, however version='7.87.0' is available. To suppress this warning, either upgrade or do the following:
>>> from cognite.client.config import global_config
>>> global_config.disable_pypi_version_check = True
  _threading_Thread_run(self)

## Check Login Status By Running Assets List

In [3]:
client.assets.list(limit=2)

AssetList([<cognite.client.data_classes.assets.Asset at 0x2c20ca58980>,
           <cognite.client.data_classes.assets.Asset at 0x2c20c9ce990>])

## Start Your Own Code Here:

In [6]:
from cognite.client.data_classes import DataSet
client.data_sets.list()
prefix = "joe_ob"
ds = client.data_sets.create(DataSet(name=prefix+"_world_info",external_id=prefix+"_data_set"))
ds

In [24]:
from cognite.client.data_classes import DataSetUpdate
my_update = DataSetUpdate(id=7335814554953330).write_protected.set(False)
res = client.data_sets.update(my_update)

In [25]:
res

In [93]:
from cognite.client.data_classes import AssetWrite
client.assets.create(AssetWrite(name="world", data_set_id=7335814554953330))

In [94]:
from cognite.client.data_classes import AssetUpdate
my_update = AssetUpdate(id=3261792952088564).name.set("global")
res = client.assets.update(my_update)

In [95]:
df = pd.read_csv("all.csv")
print(df.head())

             name alpha-2 alpha-3  country-code     iso_3166-2   region  \
0     Afghanistan      AF     AFG             4  ISO 3166-2:AF     Asia
1   Åland Islands      AX     ALA           248  ISO 3166-2:AX   Europe
2         Albania      AL     ALB             8  ISO 3166-2:AL   Europe
3         Algeria      DZ     DZA            12  ISO 3166-2:DZ   Africa
4  American Samoa      AS     ASM            16  ISO 3166-2:AS  Oceania

        sub-region intermediate-region  region-code  sub-region-code  \
0    Southern Asia                 NaN        142.0             34.0
1  Northern Europe                 NaN        150.0            154.0
2  Southern Europe                 NaN        150.0             39.0
3  Northern Africa                 NaN          2.0             15.0
4        Polynesia                 NaN          9.0             61.0

   intermediate-region-code
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN

In [97]:
clean_df = df.dropna(subset=['region'])
unique_values = clean_df['region'].unique()

for item in unique_values:
    print(item)

Asia
Europe
Africa
Oceania
Americas

In [100]:
from cognite.client.data_classes import AssetWrite
for item in unique_values:
    asset = AssetWrite(name=item, parent_id=3261792952088564, data_set_id=7335814554953330)
    client.assets.create(asset)

In [133]:
df_regions = client.assets.search(filter={"parent_ids": [3261792952088564]}).to_pandas()
df_regions

,name,parent_id,data_set_id,metadata,id,created_time,last_updated_time,root_id
0,Africa,3261792952088564,7335814554953330,{},6917770205399146,2025-10-15 22:06:20.255,2025-10-15 22:06:20.255,3261792952088564
1,Americas,3261792952088564,7335814554953330,{},5023569342550551,2025-10-15 22:59:16.775,2025-10-15 22:59:16.775,3261792952088564
2,Asia,3261792952088564,7335814554953330,{},8252367509583644,2025-10-15 22:06:19.897,2025-10-15 22:06:19.897,3261792952088564
3,Europe,3261792952088564,7335814554953330,{},2920044292887679,2025-10-15 22:06:20.075,2025-10-15 22:06:20.075,3261792952088564
4,Oceania,3261792952088564,7335814554953330,{},368024738085229,2025-10-15 22:06:20.438,2025-10-15 22:06:20.438,3261792952088564

In [103]:
lookup_value = 'Africa'
lookup_column = 'name'
target_column = 'id'
mask = df_regions[lookup_column] == lookup_value
target_id = df_regions.loc[mask, target_column].item()
print(target_id)

6917770205399146

In [134]:
assets=[]
for _, row in clean_df.iterrows():
    lookup_value = row['region']
    lookup_column = 'name'
    target_column = 'id'
    #print(lookup_value)
    mask = df_regions[lookup_column] == lookup_value
    #print(mask)
    target_id = df_regions.loc[mask, target_column].item()
    #print(target_id)
    assets.append(AssetWrite(name=row["name"], parent_id=target_id, data_set_id=7335814554953330))
    #print(assets)

client.assets.create(assets)

AssetList([<cognite.client.data_classes.assets.Asset at 0x1a827fe2970>,
           <cognite.client.data_classes.assets.Asset at 0x1a827fe3690>,
           <cognite.client.data_classes.assets.Asset at 0x1a827fe3070>,
           <cognite.client.data_classes.assets.Asset at 0x1a827fe2dd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a826bf2890>,
           <cognite.client.data_classes.assets.Asset at 0x1a826bf2190>,
           <cognite.client.data_classes.assets.Asset at 0x1a826bf20b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a825454e50>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c11d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c12b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c10f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c1550>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c3af0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c2cf0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c3230>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c2c10>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c3150>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c2f90>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c33f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c2eb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c2b30>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c1fd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c2a50>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c2970>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c20b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c2270>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c0bb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c04b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c0130>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c1c50>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c1ef0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c0910>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c3bd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c3a10>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c3cb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c3d90>,
           <cognite.client.data_classes.assets.Asset at 0x1a8280c3e70>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8050>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8130>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8210>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee82f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee83d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee84b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8590>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8670>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8750>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8830>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8910>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee89f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8ad0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8bb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8c90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8d70>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8e50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee8f30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9010>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee90f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee91d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee92b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9390>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9470>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9550>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9630>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9710>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee97f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee98d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee99b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9a90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9b70>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9c50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9d30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9e10>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9ef0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aee9fd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea0b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea190>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea270>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea350>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea430>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea510>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea5f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea6d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea7b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea890>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeea970>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeaa50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeab30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeac10>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeacf0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeadd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeaeb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeaf90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb070>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb150>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb230>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb310>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb3f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb4d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb5b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb690>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb770>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb850>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeb930>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeeba10>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeebaf0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeebbd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeebcb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeebd90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aeebe70>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0050>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0130>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0210>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed02f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed03d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed04b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0590>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0670>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0750>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0830>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0910>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed09f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0ad0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0bb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0c90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0d70>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0e50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed0f30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1010>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed10f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed11d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed12b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1390>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1470>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1550>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1630>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1710>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed17f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed18d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed19b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1a90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1b70>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1c50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1d30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1e10>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1ef0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed1fd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed20b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2190>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2270>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2350>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2430>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2510>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed25f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed26d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed27b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2890>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2970>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2a50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2b30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2c10>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2cf0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2dd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2eb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed2f90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3070>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3150>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3230>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3310>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed33f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed34d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed35b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3690>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3770>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3850>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3930>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3a10>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3af0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3bd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3cb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3d90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82aed3e70>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c050>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c130>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c210>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c2f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c3d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c4b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c590>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c670>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c750>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c830>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c910>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0c9f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0cad0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0cbb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0cc90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0cd70>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0ce50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0cf30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d010>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d0f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d1d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d2b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d390>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d470>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d550>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d630>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d710>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d7f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d8d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0d9b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0da90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0db70>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0dc50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0dd30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0de10>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0def0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0dfd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e0b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e190>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e270>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e350>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e430>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e510>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e5f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e6d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e7b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e890>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0e970>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0ea50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0eb30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0ec10>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0ecf0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0edd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0eeb0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0ef90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f070>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f150>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f230>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f310>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f3f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f4d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f5b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f690>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f770>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f850>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af0f930>])

In [139]:
client.assets.search(filter={"parent_ids": [368024738085229]})

AssetList([<cognite.client.data_classes.assets.Asset at 0x1a82af4d9b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4d710>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4d8d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4d7f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4de10>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4dc50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4db70>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4dd30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4da90>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4def0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4dfd0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e0b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e190>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e270>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e350>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e430>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e510>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e5f0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e6d0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e7b0>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e890>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4e970>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4ea50>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4eb30>,
           <cognite.client.data_classes.assets.Asset at 0x1a82af4ec10>])

In [186]:
from cognite.client.data_classes import TimeSeriesWrite

df_country_assets = client.assets.list(parent_ids=[6917770205399146,5023569342550551,8252367509583644,2920044292887679,368024738085229],limit=-1).to_pandas()

ts=[]

for _, row in df_country_assets.iterrows():
    ts.append(TimeSeriesWrite(name=row['name']+'_population', asset_id=row['id'], data_set_id=7335814554953330))

client.time_series.create(ts)

TimeSeriesList([<cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349010>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c348ad0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c3489f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c348bb0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c348c90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c348f30>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c3490f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c348d70>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c348750>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c348e50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c3491d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c3492b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349390>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349470>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349550>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349630>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349710>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c3497f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c3498d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c3499b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349a90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349b70>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349c50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349d30>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349e10>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349ef0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c349fd0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a0b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a190>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a270>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a350>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a430>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a510>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a5f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a6d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a7b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a890>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34a970>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34aa50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34ab30>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34ac10>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34acf0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34add0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34aeb0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34af90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b070>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b150>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b230>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b310>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b3f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b4d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b5b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b930>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34baf0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34ba10>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b850>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b690>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34bcb0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34bd90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34b770>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34bbd0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c34be70>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918050>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918130>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918210>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b9182f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b9183d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b9184b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918590>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918670>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918750>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918830>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918910>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b9189f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918ad0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918bb0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918c90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918d70>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918e50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b918f30>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919010>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b9190f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b9191d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b9192b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919390>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919470>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919550>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919630>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919710>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b9197f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b9198d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b9199b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919a90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919b70>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919c50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919d30>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919e10>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919ef0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b919fd0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a0b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a190>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a270>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a350>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a430>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a510>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a5f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a6d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a7b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a890>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91a970>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91aa50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91ab30>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91ac10>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91acf0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91add0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91aeb0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91af90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b070>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b150>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b230>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b310>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b3f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b4d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b5b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b690>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b770>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b850>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91b930>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91ba10>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91baf0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91bbd0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91bcb0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91bd90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82b91be70>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4050>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4130>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4210>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f42f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f43d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f44b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4590>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4670>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4750>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4830>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4910>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f49f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4ad0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4bb0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4c90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4d70>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4e50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f4f30>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5010>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f50f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f51d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f52b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5390>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5470>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5550>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5630>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5710>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f57f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f58d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f59b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5a90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5b70>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5c50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5d30>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5e10>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5ef0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f5fd0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f60b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6190>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6270>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6350>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6430>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6510>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f65f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f66d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f67b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6890>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6970>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6a50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6b30>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6c10>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6cf0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6dd0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6eb0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f6f90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7070>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7150>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7230>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7310>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f73f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f74d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f75b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7690>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7770>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7850>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7930>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7a10>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7af0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7bd0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7cb0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7d90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c4f7e70>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524050>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524130>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524210>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c5242f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c5243d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c5244b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524590>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524670>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524750>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524830>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524910>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c5249f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524ad0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524bb0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524c90>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524d70>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524e50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c524f30>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c525010>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c5250f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c5251d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c5252b0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1a82c525390>,

In [212]:
df_populations = pd.read_csv('../data/populations_postprocessed.csv')
df_populations.columns = df_populations.columns + '_population'
# Find the mapping of the time series to its id
ts_to_id = client.time_series.list(data_set_ids=[7335814554953330], limit=-1).to_pandas()[['name','id']].set_index('name')['id'].to_dict()

# Rename data frame so that columns correspond to the time seris id
df_populations = df_populations.rename(columns=ts_to_id)

df_populations['Unnamed: 0_population'] = pd.to_datetime(df_populations['Unnamed: 0_population'])
df_populations = df_populations.set_index('Unnamed: 0_population')
df_populations.head()

,3618396330788897,8965145047222557,2766775005920685,8911327919253454,4991892156625279,8004092083370245,3824630468921814,2847780117682463,6414378743723079,6062662741880158,...,4653295912986475,8519105606722058,3166157478790540,1402388318086151,6695206606317487,6871178152234874,3165374837266002,1250425371349774,8350732306419532,7204243398796248
Unnamed: 0_population,,,,,,,,,,,,,,,,,,,,,
1990-01-01,62152.0,12412311.0,11848385.0,3286542.0,54508.0,1828437.0,32618648.0,3538164.0,47351.0,62533.0,...,17354395.0,51891400.0,3109598.0,20510000.0,103963.0,146575.0,162797.0,36800507.0,8036849.0,10432409.0
1991-01-01,64623.0,13299016.0,12248901.0,3266790.0,56666.0,1937159.0,33079002.0,3505249.0,48682.0,63363.0,...,17953534.0,52000500.0,3131657.0,20952000.0,104807.0,150718.0,164000.0,37718952.0,8246662.0,10681008.0
1992-01-01,68240.0,14485543.0,12657361.0,3247039.0,58882.0,2052892.0,33529320.0,3442820.0,49900.0,64459.0,...,18561668.0,52150400.0,3154459.0,21449000.0,105712.0,155176.0,165490.0,38672611.0,8451346.0,10900511.0
1993-01-01,72495.0,15816601.0,13075044.0,3227287.0,60974.0,2173135.0,33970103.0,3363111.0,51025.0,65777.0,...,19175986.0,52179200.0,3177734.0,21942000.0,106578.0,159743.0,167117.0,39633754.0,8656484.0,11092775.0
1994-01-01,76705.0,17075728.0,13503753.0,3207536.0,62676.0,2294377.0,34402669.0,3283664.0,52099.0,67201.0,...,19793541.0,51921400.0,3201149.0,22377000.0,107318.0,164128.0,168689.0,40564061.0,8869745.0,11261752.0

In [214]:
#print(df_populations.columns.tolist())
client.time_series.data.insert_dataframe(df_populations, external_id_headers=False)

In [ ]:
from cognite.client.data_classes import filters

search_list = ["Latvia_population", "Guatemala_population", "Benin_population"]
adv_filter = filters.And(
    filters.In("name", search_list), 
    filters.Equals("data_set_id", 7335814554953330)
)
df_selected = client.time_series.filter(filter=adv_filter).to_pandas()
ds_ids = df_selected['id'].to_list()
print(ds_ids)
for item in ds_ids:
    datapoints = client.time_series.data.retrieve(id=item)
    print(datapoints)

In [236]:
adv_filter = filters.And(
    filters.Equals("parent_id", 2920044292887679),
    filters.Equals("data_set_id", 7335814554953330)
)
df_assets_in_eu = client.assets.filter(adv_filter,limit=-1).to_pandas()
assetIds_in_eu = df_assets_in_eu["id"].to_list()
print(assetIds_in_eu)
# List all time series of those assets
ts = client.time_series.list(data_set_ids=[7335814554953330],asset_ids=assetIds_in_eu, limit=-1)

# Retrieve the latest data for all of these time series
data = client.time_series.data.retrieve_latest([item.id for item in ts]).to_pandas()
data.head()
print(data.T.sum())

[418458002943973, 419620989214339, 505898643682321, 570311706761061, 588661809286109, 699868508622706, 948730200359730, 1515081802499048, 1611720636982057, 1978740915752198, 2548045025854882, 2849497442064217, 2969708084869374, 2990831008750452, 3064055882579111, 3156334080549739, 4024890163683193, 4085641824781832, 4191375203846295, 4268859580594480, 4463536705424744, 4563476888498435, 4619550905193132, 4666643101897704, 4678872124298553, 5576839006277364, 5638053639391281, 5644618907101650, 5722576523631642, 6001582726216769, 6297770812476193, 6634264154966360, 6754486054195044, 6796563220910321, 7132133650445593, 7159136754192416, 7174695683462435, 7236348311896187, 7302812702672211, 7318521408197035, 7626235710438187, 7822377665915119, 7839381849622381, 8157773008181595, 8297170099627234, 8330481482256733, 8409647551283784, 8537013786205839, 8686800262672064, 8859915377470182, 8985822931507761]
2021-01-01    656621484.0
dtype: float64

In [257]:
from pathlib import Path

folder_path = Path('../data/files')

# Use a list comprehension to iterate over all entries and filter for files
country_names_with_uploads = [
    p.name.removesuffix('.pdf') for p in folder_path.iterdir() if p.is_file()
]

print(f"COUNT: {len(country_names_with_uploads)}")

COUNT: 25

In [261]:
df_assets = client.assets.list(data_set_ids=[7335814554953330], limit=-1).to_pandas()

mask = df_assets['name'].isin(country_names_with_uploads)

df_matching_asset_ids = df_assets.loc[mask, ['id', 'name']]
df_matching_asset_ids

                   id                                               name
36   1382017945922732                                           Honduras
43   1598941891247718                                              Yemen
45   1606994126893679                                            Tokelau
51   1978740915752198  United Kingdom of Great Britain and Northern I...
52   2019924438529673                                            Vanuatu
54   2058557760485138                                             Rwanda
58   2137227535917371                                            Comoros
60   2304923158120065                                            Liberia
61   2324636893050808                                             Zambia
75   2849497442064217                                         San Marino
82   3141786740586082                                              Ghana
95   3427416635332706                                          Mauritius
101  3771349867470787                                             Jordan
128  4619550905193132                                            Finland
132  4705954984526109                                         Kyrgyzstan
149  5324935266072873                                               Oman
173  6338154911680145                                          Nicaragua
187  6794724750077368                                           Djibouti
199  7180228942616056                                            Eritrea
205  7318521408197035                                            Albania
208  7438706785357129                                             Bhutan
234  8412714252518581                                     Western Sahara
235  8443761847284906                                              Qatar
237  8456374838635013                                               Iraq
251  8927647029652717                                              Palau

In [278]:
upload_result = df_matching_asset_ids.apply(
    lambda row: client.files.upload(
        # Pass the file path from the 'file_path' column
        path=f"../data/files/{row['name']}.pdf", 
            
        # Pass the mandatory metadata parameters
        name=f"{row['name']}_data_sheet",
        data_set_id=7335814554953330,
        asset_ids=[row['id']],
            
        # Set other optional parameters as needed
        mime_type='application/pdf', 
            
        # If you want to replace existing files, set this to True
        overwrite=False 
    ),
    # Apply the function across rows (axis=1)
    axis=1
)
    
print(f"Successfully started {len(upload_result)} file uploads.")

Successfully started 25 file uploads.

In [ ]:
df_files = client.files.list(asset_ids=[2019924438529673]).to_pandas()
df_files

In [331]:
df_events = pd.read_csv('../data/events.csv', keep_default_na=False)
print(df_events)

           Dis No Disaster Group Disaster Subgroup        Disaster Type  \
0   2011-0159-ESP        Natural       Geophysical           Earthquake
1   2010-0170-ISL        Natural       Geophysical    Volcanic activity
2   2010-0574-SRB        Natural       Geophysical           Earthquake
3   2012-0152-BGR        Natural       Geophysical           Earthquake
4   2013-0121-HUN        Natural       Geophysical           Earthquake
5   2012-0142-ITA        Natural       Geophysical           Earthquake
6   2012-0162-ITA        Natural       Geophysical           Earthquake
7   2014-0049-GRC        Natural       Geophysical           Earthquake
8   2014-0174-GRC        Natural       Geophysical           Earthquake
9   2017-0182-GRC        Natural       Geophysical           Earthquake
10  2017-0280-GRC        Natural       Geophysical           Earthquake
11  2017-0350-CHE        Natural       Geophysical  Mass movement (dry)
12  2016-0313-ITA        Natural       Geophysical           Earthquake
13  2016-0357-ITA        Natural       Geophysical           Earthquake
14  2016-0358-ITA        Natural       Geophysical           Earthquake
15  2016-0335-MKD        Natural       Geophysical           Earthquake
16  2017-0015-ITA        Natural       Geophysical           Earthquake
17  2017-0349-ITA        Natural       Geophysical           Earthquake
18  2018-0461-ITA        Natural       Geophysical    Volcanic activity
19  2019-0232-ALB        Natural       Geophysical           Earthquake
20  2019-0444-ALB        Natural       Geophysical           Earthquake
21  2019-0572-ALB        Natural       Geophysical           Earthquake
22  2019-0551-FRA        Natural       Geophysical           Earthquake
23  2020-0466-GRC        Natural       Geophysical           Earthquake
24  2020-0106-HRV        Natural       Geophysical           Earthquake
25  2020-0572-HRV        Natural       Geophysical           Earthquake
26  2021-0134-GRC        Natural       Geophysical           Earthquake
27  2021-0627-GRC        Natural       Geophysical           Earthquake
28  2022-0231-BIH        Natural       Geophysical           Earthquake

   Disaster Subtype        Event Name                 Country  ISO  \
0   Ground movement                                     Spain  ESP
1          Ash fall  Eyjafjallajokull                 Iceland  ISL
2   Ground movement                                    Serbia  SRB
3   Ground movement                                  Bulgaria  BGR
4   Ground movement                                   Hungary  HUN
5   Ground movement                                     Italy  ITA
6   Ground movement                                     Italy  ITA
7   Ground movement                                    Greece  GRC
8   Ground movement                                    Greece  GRC
9   Ground movement                                    Greece  GRC
10  Ground movement                                    Greece  GRC
11         Rockfall                               Switzerland  CHE
12  Ground movement                                     Italy  ITA
13  Ground movement                                     Italy  ITA
14  Ground movement                                     Italy  ITA
15  Ground movement                           North Macedonia  MKD
16  Ground movement                                     Italy  ITA
17  Ground movement                                     Italy  ITA
18             None        Mount Etna                   Italy  ITA
19  Ground movement                                   Albania  ALB
20  Ground movement                                   Albania  ALB
21  Ground movement                                   Albania  ALB
22  Ground movement                                    France  FRA
23  Ground movement                                    Greece  GRC
24  Ground movement                                   Croatia  HRV
25  Ground movement                                   Croatia  HRV
26  Ground movement                                    Greece  GRC
27  Ground movement                                    Greece  GRC
28  Ground movement                    Bosnia and Herzegovina  BIH

             Region Continent  \
0   Southern Europe    Europe
1   Northern Europe    Europe
2   Southern Europe    Europe
3    Eastern Europe    Europe
4    Eastern Europe    Europe
5   Southern Europe    Europe
6   Southern Europe    Europe
7   Southern Europe    Europe
8   Southern Europe    Europe
9   Southern Europe    Europe
10  Southern Europe    Europe
11   Western Europe    Europe
12  Southern Europe    Europe
13  Southern Europe    Europe
14  Southern Europe    Europe
15  Southern Europe    Europe
16  Southern Europe    Europe
17  Southern Europe    Europe
18  Southern Europe    Europe
19  Southern Europe    Europe
20  Southern Europe    Europe
21  Southern Europe    Europe
22   Western Europe    Europe
23  Southern Europe    Europe
24  Southern Europe    Europe
25  Southern Europe    Europe
26  Southern Europe    Europe
27  Southern Europe    Europe
28  Southern Europe    Europe

                                             Location Origin  Start Year  \
0   Lorca municipality (Murcia district, Region de...               2011
1    Fljotshlid, Eyjafjöll, and Landeyjar villages...               2010
2                      Kraljevo town (Raski Province)               2010
3   Pernik town (Pernik Province), Sofia town (Sof...               2012
4                                      Heves province               2013
5   Finale Emilia, Mirandola towns (Modena Provinc...               2012
6             Modena Province (Emilia-romagna Region)               2012
7   Lixouri, Kounopetra, Fiskardo villages (Kefalo...               2014
8   Limnos Island (Lesvou district, Voreio Aigaio ...               2014
9   Vrisa, Plomarion,Plagias, Chios, Kampas, Skala...               2017
10                                         Kos Island               2017
11       Bregaglia Valley, Bondo in Graubünden canton               2017
12  Amatrice, Accumoli, Pescara del Tronto, Arquat...               2016
13  Visso, Ussita (Macerata district, Marche provi...               2016
14         Norcia (Perugia district, Umbria province)               2016
15                                    Skopje province               2016
16  Avezzano, Campotosto, Montereale, Capitignano,...               2017
17  Casamicciola Terme, Lacco Ameno (Ischia Isl.),...               2017
18  Acicatena, Acireale, Aci Sant’Antonio, Santa V...               2018
19                                       Korçë county               2019
20                            Durres, Tirana Counties               2019
21                       Durrës, Kruje, Tiranë, Lezhë               2019
22                       Auvergne-Rhône-Alpes region                2019
23                                              Samos               2020
24                                             Zagreb               2020
25  Sisak, Petrinja, Glina, Hrvatska Kostajnica, Z...               2020
26  Larissa, Elassona (Larisis) , Tyrnavos (Larisi...               2021
27  Arkalochori, Archontiko, Roussochoria, Patside...               2021
28                              Ljubinje and Capljina               2022

    Start Month  Start Day  End Year  End Month  End Day
0             5         11      2011          5       11
1             3          1      2010          4       28
2            11          3      2010         11        3
3             5         22      2012          5       22
4             4         14      2013          4       23
5             5         20      2012          5       20
6             5         29      2012          5       29
7             1         26      2014          2        3
8             5         24      2014          5       24
9             6         12      2017          6       12
10            7         21      2017          7       21
11            8         23      2017          8       23
12            8         24      2016          8       24
13           10         26      2016         10       26
14           10         30      2016         10       30
15            9         11      2016          9       11
16            1         18      2017          1       19
17            8         23      2017          8       23
18           12         24      2018         12       26
19            6          1      2019          6        1
20            9         21      2019          9       21
21           11         26      2019         11       26
22           11         11      2019         11       11
23           10         30      2020         10       30
24            3         22      2020          3       22
25           12         29      2020         12       29
26            3          3      2021          3        3
27            9         27      2021          9       27
28            4         23      2022          4       23

In [332]:
def find_asset_ids_by_country_names(country_name_list):
    df_assets = client.assets.list(data_set_ids=[7335814554953330], limit=-1).to_pandas()
    mask = df_assets['name'].isin(country_name_list)
    return df_assets.loc[mask, ['id', 'name']]

country_names = df_events['Country'].unique().tolist()
df_asset_lookup = find_asset_ids_by_country_names(country_names)
df_asset_lookup.rename(columns={'name': 'Country', 'id': 'Asset ID'}, inplace=True)
df_events = df_events.merge(
    df_asset_lookup,
    on='Country',
    how='left'
)
df_events

,Dis No,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Event Name,Country,ISO,Region,Continent,Location,Origin,Start Year,Start Month,Start Day,End Year,End Month,End Day,Asset ID
0,2011-0159-ESP,Natural,Geophysical,Earthquake,Ground movement,,Spain,ESP,Southern Europe,Europe,"Lorca municipality (Murcia district, Region de...",,2011,5,11,2011,5,11,4563476888498435
1,2010-0170-ISL,Natural,Geophysical,Volcanic activity,Ash fall,Eyjafjallajokull,Iceland,ISL,Northern Europe,Europe,"Fljotshlid, Eyjafjöll, and Landeyjar villages...",,2010,3,1,2010,4,28,6297770812476193
2,2010-0574-SRB,Natural,Geophysical,Earthquake,Ground movement,,Serbia,SRB,Southern Europe,Europe,Kraljevo town (Raski Province),,2010,11,3,2010,11,3,6796563220910321
3,2012-0152-BGR,Natural,Geophysical,Earthquake,Ground movement,,Bulgaria,BGR,Eastern Europe,Europe,"Pernik town (Pernik Province), Sofia town (Sof...",,2012,5,22,2012,5,22,8859915377470182
4,2013-0121-HUN,Natural,Geophysical,Earthquake,Ground movement,,Hungary,HUN,Eastern Europe,Europe,Heves province,,2013,4,14,2013,4,23,3156334080549739
5,2012-0142-ITA,Natural,Geophysical,Earthquake,Ground movement,,Italy,ITA,Southern Europe,Europe,"Finale Emilia, Mirandola towns (Modena Provinc...",,2012,5,20,2012,5,20,699868508622706
6,2012-0162-ITA,Natural,Geophysical,Earthquake,Ground movement,,Italy,ITA,Southern Europe,Europe,Modena Province (Emilia-romagna Region),,2012,5,29,2012,5,29,699868508622706
7,2014-0049-GRC,Natural,Geophysical,Earthquake,Ground movement,,Greece,GRC,Southern Europe,Europe,"Lixouri, Kounopetra, Fiskardo villages (Kefalo...",,2014,1,26,2014,2,3,2548045025854882
8,2014-0174-GRC,Natural,Geophysical,Earthquake,Ground movement,,Greece,GRC,Southern Europe,Europe,"Limnos Island (Lesvou district, Voreio Aigaio ...",,2014,5,24,2014,5,24,2548045025854882
9,2017-0182-GRC,Natural,Geophysical,Earthquake,Ground movement,,Greece,GRC,Southern Europe,Europe,"Vrisa, Plomarion,Plagias, Chios, Kampas, Skala...",,2017,6,12,2017,6,12,2548045025854882
10,2017-0280-GRC,Natural,Geophysical,Earthquake,Ground movement,,Greece,GRC,Southern Europe,Europe,Kos Island,,2017,7,21,2017,7,21,2548045025854882
11,2017-0350-CHE,Natural,Geophysical,Mass movement (dry),Rockfall,,Switzerland,CHE,Western Europe,Europe,"Bregaglia Valley, Bondo in Graubünden canton",,2017,8,23,2017,8,23,8157773008181595
12,2016-0313-ITA,Natural,Geophysical,Earthquake,Ground movement,,Italy,ITA,Southern Europe,Europe,"Amatrice, Accumoli, Pescara del Tronto, Arquat...",,2016,8,24,2016,8,24,699868508622706
13,2016-0357-ITA,Natural,Geophysical,Earthquake,Ground movement,,Italy,ITA,Southern Europe,Europe,"Visso, Ussita (Macerata district, Marche provi...",,2016,10,26,2016,10,26,699868508622706
14,2016-0358-ITA,Natural,Geophysical,Earthquake,Ground movement,,Italy,ITA,Southern Europe,Europe,"Norcia (Perugia district, Umbria province)",,2016,10,30,2016,10,30,699868508622706
15,2016-0335-MKD,Natural,Geophysical,Earthquake,Ground movement,,North Macedonia,MKD,Southern Europe,Europe,Skopje province,,2016,9,11,2016,9,11,7132133650445593
16,2017-0015-ITA,Natural,Geophysical,Earthquake,Ground movement,,Italy,ITA,Southern Europe,Europe,"Avezzano, Campotosto, Montereale, Capitignano,...",,2017,1,18,2017,1,19,699868508622706
17,2017-0349-ITA,Natural,Geophysical,Earthquake,Ground movement,,Italy,ITA,Southern Europe,Europe,"Casamicciola Terme, Lacco Ameno (Ischia Isl.),...",,2017,8,23,2017,8,23,699868508622706
18,2018-0461-ITA,Natural,Geophysical,Volcanic activity,None,Mount Etna,Italy,ITA,Southern Europe,Europe,"Acicatena, Acireale, Aci Sant’Antonio, Santa V...",,2018,12,24,2018,12,26,699868508622706
19,2019-0232-ALB,Natural,Geophysical,Earthquake,Ground movement,,Albania,ALB,Southern Europe,Europe,Korçë county,,2019,6,1,2019,6,1,7318521408197035
20,2019-0444-ALB,Natural,Geophysical,Earthquake,Ground movement,,Albania,ALB,Southern Europe,Europe,"Durres, Tirana Counties",,2019,9,21,2019,9,21,7318521408197035
21,2019-0572-ALB,Natural,Geophysical,Earthquake,Ground movement,,Albania,ALB,Southern Europe,Europe,"Durrës, Kruje, Tiranë, Lezhë",,2019,11,26,2019,11,26,7318521408197035
22,2019-0551-FRA,Natural,Geophysical,Earthquake,Ground movement,,France,FRA,Western Europe,Europe,Auvergne-Rhône-Alpes region,,2019,11,11,2019,11,11,2969708084869374
23,2020-0466-GRC,Natural,Geophysical,Earthquake,Ground movement,,Greece,GRC,Southern Europe,Europe,Samos,,2020,10,30,2020,10,30,2548045025854882
24,2020-0106-HRV,Natural,Geophysical,Earthquake,Ground movement,,Croatia,HRV,Southern Europe,Europe,Zagreb,,2020,3,22,2020,3,22,7626235710438187
25,2020-0572-HRV,Natural,Geophysical,Earthquake,Ground movement,,Croatia,HRV,Southern Europe,Europe,"Sisak, Petrinja, Glina, Hrvatska Kostajnica, Z...",,2020,12,29,2020,12,29,7626235710438187
26,2021-0134-GRC,Natural,Geophysical,Earthquake,Ground movement,,Greece,GRC,Southern Europe,Europe,"Larissa, Elassona (Larisis) , Tyrnavos (Larisi...",,2021,3,3,2021,3,3,2548045025854882
27,2021-0627-GRC,Natural,Geophysical,Earthquake,Ground movement,,Greece,GRC,Southern Europe,Europe,"Arkalochori, Archontiko, Roussochoria, Patside...",,2021,9,27,2021,9,27,2548045025854882
28,2022-0231-BIH,Natural,Geophysical,Earthquake,Ground movement,,Bosnia and Herzegovina,BIH,Southern Europe,Europe,Ljubinje and Capljina,,2022,4,23,2022,4,23,2990831008750452

In [345]:
from cognite.client.data_classes import EventWrite
from dateutil.parser import parse
from dateutil.parser import ParserError
from datetime import datetime, timezone

def is_valid_date(date_string):
    # Checks if a string can be parsed into a valid date object
    try:
        # Attempt to parse the string into a datetime object
        parse(date_string)
        return True
    except (ValueError, TypeError, ParserError):
        # Catches common errors if the string is not a valid date
        return False

def convert_to_epoch_format(date_str):
    date_format = "%Y-%m-%d"
    dt_object = datetime.strptime(date_str, date_format)
    epoch_seconds = dt_object.replace(tzinfo=timezone.utc).timestamp()
    epoch_milliseconds = int(epoch_seconds * 1000)
    return epoch_milliseconds

def create_event_obj(start_date, end_date, dis_type, dis_stype, loc, asset_id):
    if is_valid_date(start_date) and is_valid_date(end_date):
        start_date_int = convert_to_epoch_format(start_date)
        end_date_int = convert_to_epoch_format(end_date)
    else:
        print("failed in conversion")
        return False
    dict_loc = {"Location": loc}
    return EventWrite(start_time=start_date_int, end_time=end_date_int, type=dis_type, subtype=dis_stype, metadata=dict_loc, data_set_id=7335814554953330, asset_ids=[asset_id])

def create_event_writes(df) -> list[EventWrite]:
    list_of_dicts = df.to_dict('records')
    event_list = [
        create_event_obj(
            f"{row['Start Year']}-{row['Start Month']}-{row['Start Day']}",
            f"{row['End Year']}-{row['End Month']}-{row['End Day']}",
            row['Disaster Type'],
            row['Disaster Subtype'],
            row['Location'],
            row['Asset ID']
        )
        for row in list_of_dicts
    ]    
    return event_list

list_of_event_writes = create_event_writes(df_events)
res = client.events.create(list_of_event_writes)

In [351]:
adv_filter = filters.And(
    filters.Equals("data_set_id", 7335814554953330),
    filters.Equals("type", "Volcanic activity")
)
volcanic_events_list = client.events.filter(adv_filter)
volcanic_events_list

EventList([<cognite.client.data_classes.events.Event at 0x1a82e6bfa10>,
           <cognite.client.data_classes.events.Event at 0x1a82e6bf4d0>,
           <cognite.client.data_classes.events.Event at 0x1a82e6bfad0>,
           <cognite.client.data_classes.events.Event at 0x1a82e6bf950>])

In [ ]:
res = client.time_series.search(name='Netherlands')
print(res)
from cognite.client.data_classes import TimeSeriesUpdate
my_update = TimeSeriesUpdate(id=2527585060365203).name.set("Netherlands_population")
res = client.time_series.update(my_update)
print(res)
#tss = TimeSeriesWrite(name='Netherlands_population', asset_id=row['id'], data_set_id=7335814554953330)

#client.time_series.create(tss)

In [7]:
client.labels.list(name="Hot")

LabelDefinitionList([<cognite.client.data_classes.labels.LabelDefinition at 0x2436f753b60>])

In [7]:
client.labels.list(name="Hot")

LabelDefinitionList([<cognite.client.data_classes.labels.LabelDefinition at 0x2436f753b60>])

In [8]:
#df = client.assets.list(data_set_ids=[7335814554953330], limit=-1).to_pandas()
#res = client.assets.delete(id=df["id"].tolist())
#df = client.time_series.list(data_set_ids=[7335814554953330], limit=-1).to_pandas()
#res = client.time_series.delete(id=df["id"].tolist())
#df = client.files.list(data_set_ids=[7335814554953330], limit=-1).to_pandas()
#res = client.files.delete(id=df["id"].tolist())
df = client.events.list(data_set_ids=[7335814554953330], limit=-1).to_pandas()
res = client.events.delete(id=df["id"].tolist())

In [9]:
res